import type { VinylRecord } from "./types"

// Activated only in development (NODE_ENV === 'development')
// Cover images: picsum.photos/seed/<slug>/300/300 — deterministic, always the same image per seed

export const MOCK_RECORDS: VinylRecord[] = [
  {
    id: "mock-1",
    title: "Kind of Blue",
    artist: "Miles Davis",
    year: 1959,
    genre: "Jazz",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/kindofblue/300/300",
    notes: "Original Columbia pressing, inner sleeve intact",
    dateAdded: "2024-11-10",
    addedBy: "gsaraiva",
    addedByAvatar: undefined,
    discogs: { releaseId: "5785467", value: 120, wantlistCount: 4821 },
    spotify: { albumId: "1weenld61qoidwYuZ1GESA" },
  },
  {
    id: "mock-2",
    title: "Rumours",
    artist: "Fleetwood Mac",
    year: 1977,
    genre: "Rock",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/rumours/300/300",
    dateAdded: "2024-10-22",
    addedBy: "gsaraiva",
    discogs: { releaseId: "2384506", value: 38, wantlistCount: 12300 },
    spotify: { albumId: "1bt6q2SruMsBtcerNVtpZB" },
  },
  {
    id: "mock-3",
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Pop",
    condition: "VG",
    coverUrl: "https://picsum.photos/seed/thriller/300/300",
    dateAdded: "2024-09-05",
    addedBy: "gsaraiva",
    discogs: { releaseId: "371252", value: 22, wantlistCount: 9200 },
    spotify: { albumId: "2ANVost0y2y52ema1E9xAZ" },
  },
  {
    id: "mock-4",
    title: "Abbey Road",
    artist: "The Beatles",
    year: 1969,
    genre: "Rock",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/abbeyroad/300/300",
    notes: "UK Apple pressing, minimal ring wear",
    dateAdded: "2024-08-14",
    addedBy: "gsaraiva",
    discogs: { releaseId: "16860799", value: 95, wantlistCount: 22100 },
    spotify: { albumId: "0ETFjACtuP2ADo6LFhL6HN" },
  },
  {
    id: "mock-5",
    title: "Purple Rain",
    artist: "Prince",
    year: 1984,
    genre: "Pop",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/purplerain/300/300",
    dateAdded: "2024-12-01",
    addedBy: "gsaraiva",
    discogs: { releaseId: "505753", value: 55, wantlistCount: 7800 },
    spotify: { albumId: "1LkjFCEKyMBRqU8PJBC9pE" },
  },
  {
    id: "mock-6",
    title: "What's Going On",
    artist: "Marvin Gaye",
    year: 1971,
    genre: "Soul",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/whatsgoingon/300/300",
    notes: "Tamla US pressing, still crisp",
    dateAdded: "2024-07-30",
    addedBy: "gsaraiva",
    discogs: { releaseId: "633497", value: 78, wantlistCount: 5600 },
    spotify: { albumId: "4eLPsYPBmXABThSJ821sqY" },
  },
  {
    id: "mock-7",
    title: "Nevermind",
    artist: "Nirvana",
    year: 1991,
    genre: "Rock",
    condition: "VG",
    coverUrl: "https://picsum.photos/seed/nevermind/300/300",
    dateAdded: "2024-06-12",
    addedBy: "gsaraiva",
    discogs: { releaseId: "43906", value: 30, wantlistCount: 18200 },
    spotify: { albumId: "2UJcKiJxNryhL050F5Z1Fk" },
  },
  {
    id: "mock-8",
    title: "Homework",
    artist: "Daft Punk",
    year: 1997,
    genre: "Electronic",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/homework/300/300",
    dateAdded: "2024-11-28",
    addedBy: "gsaraiva",
    discogs: { releaseId: "3685", value: 62, wantlistCount: 3400 },
    spotify: { albumId: "6xyFsF8NMXGaOJhCEI9KiB" },
  },
  {
    id: "mock-9",
    title: "Illmatic",
    artist: "Nas",
    year: 1994,
    genre: "Hip-Hop",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/illmatic/300/300",
    notes: "Sealed repress from 2014",
    dateAdded: "2024-10-03",
    addedBy: "gsaraiva",
    discogs: { releaseId: "415553", value: 44, wantlistCount: 11000 },
    spotify: { albumId: "3kEtdS2pH5NMomqHm0KXCK" },
  },
  {
    id: "mock-10",
    title: "Blue",
    artist: "Joni Mitchell",
    year: 1971,
    genre: "Folk",
    condition: "G",
    coverUrl: "https://picsum.photos/seed/jonimitchellblue/300/300",
    notes: "Some crackle on side A, plays through fine",
    dateAdded: "2024-05-20",
    addedBy: "gsaraiva",
    discogs: { releaseId: "2234095", value: 18, wantlistCount: 8700 },
  },
  {
    id: "mock-11",
    title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    year: 1973,
    genre: "Rock",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/darksidedmoon/300/300",
    notes: "UK Harvest first press, complete with posters",
    dateAdded: "2024-04-18",
    addedBy: "gsaraiva",
    discogs: { releaseId: "10414517", value: 140, wantlistCount: 19800 },
    spotify: { albumId: "4LH4d3cOWNNsVw41Gqt2kv" },
  },
  {
    id: "mock-12",
    title: "Random Access Memories",
    artist: "Daft Punk",
    year: 2013,
    genre: "Electronic",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/randomaccess/300/300",
    dateAdded: "2024-12-10",
    addedBy: "gsaraiva",
    discogs: { releaseId: "4555800", value: 48, wantlistCount: 6200 },
    spotify: { albumId: "4m2880jivSbbyEGAKfITCa" },
  },
  {
    id: "mock-13",
    title: "Sticky Fingers",
    artist: "The Rolling Stones",
    year: 1971,
    genre: "Rock",
    condition: "VG",
    coverUrl: "https://picsum.photos/seed/stickyfingers/300/300",
    dateAdded: "2024-03-07",
    addedBy: "gsaraiva",
    discogs: { releaseId: "6557", value: 35, wantlistCount: 5100 },
    spotify: { albumId: "5LBgIRHKXGJCXpx5FVBDDQ" },
  },
  {
    id: "mock-14",
    title: "Endtroducing.....",
    artist: "DJ Shadow",
    year: 1996,
    genre: "Electronic",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/endtroducing/300/300",
    notes: "Mo' Wax UK press, hype sticker still on",
    dateAdded: "2024-09-19",
    addedBy: "gsaraiva",
    discogs: { releaseId: "7964", value: 85, wantlistCount: 4200 },
    spotify: { albumId: "1mLqUvSMeJPnhC04GEq4tg" },
  },
  {
    id: "mock-15",
    title: "Innervisions",
    artist: "Stevie Wonder",
    year: 1973,
    genre: "Soul",
    condition: "VG",
    coverUrl: "https://picsum.photos/seed/innervisions/300/300",
    dateAdded: "2024-02-14",
    addedBy: "gsaraiva",
    discogs: { releaseId: "1042474", value: 25, wantlistCount: 3800 },
    spotify: { albumId: "4VqPOruhp5EdPBeR92t6lQ" },
  },
  {
    id: "mock-16",
    title: "Remain in Light",
    artist: "Talking Heads",
    year: 1980,
    genre: "Electronic",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/remaininlight/300/300",
    notes: "Sire US original, plays dead quiet",
    dateAdded: "2024-08-01",
    addedBy: "gsaraiva",
    discogs: { releaseId: "51565", value: 58, wantlistCount: 4900 },
    spotify: { albumId: "3HsPKHd4TMCIxbcJZVLCTM" },
  },
  {
    id: "mock-17",
    title: "London Calling",
    artist: "The Clash",
    year: 1979,
    genre: "Punk",
    condition: "G",
    coverUrl: "https://picsum.photos/seed/londoncalling/300/300",
    notes: "Heavily played, still a banger",
    dateAdded: "2024-01-30",
    addedBy: "gsaraiva",
    discogs: { releaseId: "9392", value: 20, wantlistCount: 6500 },
  },
  {
    id: "mock-18",
    title: "Let's Get It On",
    artist: "Marvin Gaye",
    year: 1973,
    genre: "Soul",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/letsgetiton/300/300",
    dateAdded: "2024-12-20",
    addedBy: "gsaraiva",
    discogs: { releaseId: "370762", value: 42, wantlistCount: 4600 },
    spotify: { albumId: "5HRpECzHjKLMUsWBOxQJGH" },
  },
  {
    id: "mock-19",
    title: "The College Dropout",
    artist: "Kanye West",
    year: 2004,
    genre: "Hip-Hop",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/collegedropout/300/300",
    dateAdded: "2024-07-07",
    addedBy: "gsaraiva",
    discogs: { releaseId: "1484949", value: 33, wantlistCount: 8800 },
    spotify: { albumId: "4SZko61aMnmgvNhfhgTuD3" },
  },
  {
    id: "mock-20",
    title: "Disintegration",
    artist: "The Cure",
    year: 1989,
    genre: "Rock",
    condition: "NM",
    coverUrl: "https://picsum.photos/seed/disintegration/300/300",
    notes: "Fiction Records UK press",
    dateAdded: "2024-06-30",
    addedBy: "gsaraiva",
    discogs: { releaseId: "167049", value: 67, wantlistCount: 5300 },
    spotify: { albumId: "5COXoP5kj2DWfCDg0vxi4F" },
  },
  {
    id: "mock-21",
    title: "Debut",
    artist: "Björk",
    year: 1993,
    genre: "Electronic",
    condition: "VG",
    coverUrl: "https://picsum.photos/seed/bjorkdebut/300/300",
    dateAdded: "2024-05-05",
    addedBy: "gsaraiva",
    discogs: { releaseId: "36668", value: 28, wantlistCount: 2900 },
    spotify: { albumId: "4ehCLiKGAqkDzDcRUKWMOJ" },
  },
  {
    id: "mock-22",
    title: "Madvillainy",
    artist: "Madvillain",
    year: 2004,
    genre: "Hip-Hop",
    condition: "M",
    coverUrl: "https://picsum.photos/seed/madvillainy/300/300",
    notes: "Stones Throw reissue, limited color vinyl",
    dateAdded: "2024-11-15",
    addedBy: "gsaraiva",
    discogs: { releaseId: "1483162", value: 72, wantlistCount: 14200 },
    spotify: { albumId: "19bQiwEKhXUBJWY6oV3KZk" },
  },
]
