version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vinyl-catalog"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "electron"

  - package-ecosystem: "npm"
    directory: "/vinyl-catalog/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "npm"
    directory: "/vinylRecognizerDashboard"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
